config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  get 'static_pages/top'
  resources :questions, only: [:index, :create] do
    collection do
      get :result
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :choices, dependent: :destroy
end

app/models/result.rb
class Result < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def create
    answers = answers = diagnosis_question_params.values
    total_score = answers.map(&:to_i).sum
    session[:total_score] = total_score
    redirect_to result_questions_path
  end

  def result
    total_score = session[:total_score]
    if total_score
      @diagnosis_result = Result.find_by("min_score <= ? AND max_score >= ?", total_score, total_score)
      session.delete(:total_score)
    else
      redirect_to root_path, danger: "診断し直してください"
      return
    end
  end

  private

  def diagnosis_question_params
    params.require(:result).permit(:answer_1, :answer_2, :answer_3, :answer_4, :answer_5, :answer_6, :answer_7, :answer_8, :answer_9, :answer_10)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: 'PersonalShindan',
      title: '個性診断サービス',
      reverse: true,
      charset: 'utf-8',
      description: '個性の診断をすることができます',
      keywords: '診断,個性,性格',
      canonical: request.original_url,
      separator: '|',
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: 'website',
        url: request.original_url,
        image: image_url('ogp.png'),
        local: 'ja-JP'
      },
      # Twitter用の設定を個別で設定する
      twitter: {
        card: 'summary_large_image', # Twitterで表示する場合は大きいカードにする
        image: image_url('ogp.png') # 配置するパスやファイル名によって変更すること
      }
    }
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>個性診断</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= display_meta_tags(default_meta_tags) %>
  </head>

  <body>
    <%= render 'shared/flash_message' %>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<div class="bg-diagnosis min-h-screen text-customBlue font-mono flex flex-col items-center justify-center">
  <h2 id="start-description" class="text-lg font-bold bg-clip-text text-transparent bg-gradient-to-r from-customBlue to-customPurple sm:tracking-wider sm:font-extrabold sm:text-2xl">✨あなたの秘密の個性を探る10の質問✨</h2>
  <button id="start-diagnosis" type="button" class='bg-customBlue3 text-customBlue4 text-sm mt-10 mb-2 py-2 px-4 border-2 border-customSky5 rounded-xl hover:bg-customSky5 hover:border-customBlue3'>診断する</button>
  <div class="w-full">
    <%= form_with(scope: :result, url: questions_path, method: :post, local: true,class: 'w-full ') do |f| %>
      <div class='error-message hidden px-10 py-2 mb-10 mx-10 text-sm text-red-800 bg-red-100 rounded-xl dark:bg-red-100 dark:text-red-800' id="error_message">選択してください</div>
      <% @questions.each_with_index do |question, index| %>
        <div id='question_<%= question.id %>', class='hidden lg:w-1/3 md:w-4/5 sm:w-5/6 flex flex-col items-center justify-center text-customOrange mx-auto w-full px-8 py-2 bg-customBlue3 border-2 border-customOrange rounded-2xl drop-shadow-xl'>
          <p class="my-10 text-2xl font-bold tracking-wide text-white"><%= question.text %></p>
          <div class="container w-full sm:w-2/5 sm:mx-auto ">
            <% question.choices.each do |choice| %>
              <div class="mt-2 w-5/6 sm:w-48 sm:mx-auto text-customOrange">
                <%= f.radio_button "answer_#{question.id}", choice.score, class:'border-2 border-customOrange bg-customOrange4' %>
                <%= f.label :answer, choice.text, value: choice.score, class:'ml-2 text-base'%>
              </div>
            <% end %>
          </div>
          <div class="flex justify-evenly text-customBrown5">
            <% unless index == @questions.length - 10 %>
              <button type="button" data-action="previous-question" id='button_<%=question.id%>' class='bg-customSky border-2 border-customSky3 mt-10 mb-4 mx-2 py-2 px-6 rounded-full drop-shadow-xl text-sm hover:bg-customSky3 hover:border-customSky hover:border-2'>戻る</button>
            <% end %>
            <% unless index == @questions.length - 1 %>
              <button type="button" data-action="next-question" id='button_<%=question.id%>' class=' bg-customSky2 border-2 border-customSky4 mt-10 mb-4 mx-2 py-2 px-6 rounded-full drop-shadow-xl text-sm hover:bg-customSky4 hover:border-customSky2 hover:border-2'>次へ</button>
            <% end %>
          </div>
        </div>
      <% end %>
      <div class="flex justify-evenly text-customOrange3">
        <%= f.submit "診断結果", data: { action: "submit-button" }, class: 'hidden bg-customBlue3 text-customBlue4 text-sm mt-10 mb-2 py-2 px-4 border-2 border-customSky5 rounded-xl hover:bg-customSky5 hover:border-customBlue3', id: 'submit-button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/result.html.erb
<div class="result-image text-2xl sm:text-4xl font-mono h-screen font-mono flex flex-col items-center justify-center">
  <div class="my-10 font-extrabold">
    <h2 class="tracking-wider bg-clip-text text-transparent bg-gradient-to-r from-customBlue to-customPurple">⭐️あなたの診断結果⭐️</h2>
  </div>
  <div>
    <p class="container mx-auto w-2/3 text-base font-light sm:text-lg text-center text-customBlue5 sm:w-2/3 md:w-3/5 lg:w-1/2" ><%= @diagnosis_result.description%></p>
  </div>
  <div class="bg-customBlue3 text-customBlue4 text-sm mt-10 mb-2 py-2 px-4 border-2 border-customSky5 rounded-xl hover:bg-customSky5 hover:border-customBlue3">
    <%= link_to "もう一度診断する", questions_path%>
  </div>
  <div class="twitter text-sm text-gray-700 my-6 py-1 px-4 border-2 border-gray-500 rounded-xl hover:bg-gray-200">
    <%= link_to "https://twitter.com/share?url=https://personal-shindan-app.onrender.com&text=【診断結果】%0a%0a#{ @diagnosis_result.description}", target: '_blank' do %>
      <i class="fa-brands fa-x-twitter"></i>シェア
    <% end %>
  </div>
</div>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == 'success' || message_type == 'notice' %>
    <div class="p-4 text-sm text-emerald-800 bg-emerald-100 dark:bg-emerald-100 dark:text-emerald-800" role="alert">
      <%= message %>
    </div>
  <% elsif message_type == 'danger' %>
    <div class="p-4 text-sm text-red-800 bg-red-100 dark:bg-red-100 dark:text-red-800" role="alert">
      <%= message %>
    </div>
  <% elsif message_type == 'warning' %>
    <div class="p-4 text-sm text-yellow-800 bg-yellow-100 dark:bg-yellow-100 dark:text-yellow-800" role="alert">
      <%= message %>
    </div>
  <% else %>
    <div class="p-4 text-sm text-sky-800 bg-sky-100 dark:bg-sky-100 dark:text-sky-800" role="alert"><%= message %></div>
  <% end %>
<% end %>

app/views/static_pages/top.html.erb
<%= link_to "診断を開始", questions_path%>